### ISSUE TITLE
Support arbitrary .lkml file types

### ISSUE THREAD

**Issue by tpakeman** [llooker/lookml#18]
It would be great to support arbitrary file extensions that end `.lkml` rather than throwing an exception (lookml.py line 629). I have worked on projects where people use all sorts of file types for organisation, like `foo.tests.lkml` or `bar.datagroups.lkml`

**Comment by tpakeman** [comment]
Potentially could implement something like this as it seems that filetypes are not really used apart from as metadata:

```
if self.name.endswith(".model.lkml"):
...
else:
    if self.name.endswith('lkml'):
        self.filetype = self.name.split('.')[-2]
    else:
        raise Exception("Unsupported filename " + self.name)
```

**Comment by russlooker** [comment]
Makes sense!  Will do

**Comment by tpakeman** [comment]
fixed in https://github.com/llooker/lookml/commit/66e78ff139a61eac9a94e602ffb4ce4cf92b7257
