### ISSUE TITLE
adding new dimensions and measures adds extra new line

### ISSUE THREAD

**Issue by bryan-at-looker** [llooker/lookml#2]
Here's the code
```
import lookml

order_items = lookml.View('order_items')
order_items.setSqlTableName(sql_table_name='events',schema='public')
order_items + 'id' + 'sale_price'
order_items.addSum(order_items.sale_price)
print(order_items)
```

Here's the output, notice the extra new line between id, sale_price and sale_price and total_sale_price
```
view: order_items {
sql_table_name: `public`.`events` ;;

dimension: id {
    type: string
    sql: ${TABLE}.`id` ;;
}

    
dimension: sale_price {
    type: string
    sql: ${TABLE}.`sale_price` ;;
}

    
measure: total_sale_price {
    type: sum
    sql: ${sale_price} ;;
}

}
```

**Comment by russlooker** [comment]
I will add this later, looking to parameterize the lookml style, dense, number of new lines characters etc

**Comment by russlooker** [comment]
This is now fixed as of the last commit:

`>>> print(x)
view: oi {


dimension: cool {
    sql: ${TABLE}.`cool` ;;
    type: string
}


dimension: id {
    sql: ${TABLE}.`id` ;;
    type: string
}

}

>>> lookml.config.PRE_FIELD_BUFFER = ''
>>> lookml.config.POST_FIELD_BUFFER = ''
>>> print(x)
view: oi {

dimension: cool {
    sql: ${TABLE}.`cool` ;;
    type: string
}
dimension: id {
    sql: ${TABLE}.`id` ;;
    type: string
}
}`
